In [29]:
for i in range(1,11):
    for j in range(i):
        print(j+1,end='')
    print()

1
12
123
1234
12345
123456
1234567
12345678
123456789
12345678910


In [37]:
for i in range(1,11):
    for j in range(i):
        print(i,end='')
    print()

1
22
333
4444
55555
666666
7777777
88888888
999999999
10101010101010101010


In [40]:
for i in range(1,11):
    for j in range(i):
        print(chr(64+i),end='')
    print()

A
BB
CCC
DDDD
EEEEE
FFFFFF
GGGGGGG
HHHHHHHH
IIIIIIIII
JJJJJJJJJJ


In [48]:
for i in range(1,11):
    for j in range(i):
        print(chr(65+j),end='')
    print()

A
AB
ABC
ABCD
ABCDE
ABCDEF
ABCDEFG
ABCDEFGH
ABCDEFGHI
ABCDEFGHIJ


In [53]:
for i in range(1,11):
    for j in range(11-i):
        print('*',end='')
    print()

**********
*********
********
*******
******
*****
****
***
**
*


In [56]:
for i in range(1,11):
    for j in range(11-i):
        print(i,end='')
    print()

1111111111
222222222
33333333
4444444
555555
66666
7777
888
99
10


In [63]:
for i in range(1,11):
    for j in range(11-i):
        print(j+1,end='')
    print()

12345678910
123456789
12345678
1234567
123456
12345
1234
123
12
1


In [69]:
for i in range(1,11):
    for j in range(11-i):
        print(chr(64+i),end='')
    print()

AAAAAAAAAA
BBBBBBBBB
CCCCCCCC
DDDDDDD
EEEEEE
FFFFF
GGGG
HHH
II
J


In [77]:
for i in range(10):
    for j in range(10-i):
        print(chr(65+i),end='')
    print()

AAAAAAAAAA
BBBBBBBBB
CCCCCCCC
DDDDDDD
EEEEEE
FFFFF
GGGG
HHH
II
J


In [86]:
for i in range(10):
    for j in range(10):
        print(chr(74-j),end='')
    print()

JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA
JIHGFEDCBA


In [92]:
for i in range(10):
    for j in range(i+1):
        print('*',end='')
    print()

*
**
***
****
*****
******
*******
********
*********
**********


In [97]:
for i in range(10):   
    for j in range(10-i):
        print('*',end='')
    print()

**********
*********
********
*******
******
*****
****
***
**
*


In [4]:
for i in range(1,11):
    for j in range(11-i):
        print(i,end='')
    print()

1111111111
222222222
33333333
4444444
555555
66666
7777
888
99
10


In [9]:
for i in range(1,11):
    for j in range(11-i):
        print(j+1,end='')
    print()

12345678910
123456789
12345678
1234567
123456
12345
1234
123
12
1


In [10]:
for i in range(1,11):
    for j in range(11-i):
        print(chr(64+i),end='')
    print() 

AAAAAAAAAA
BBBBBBBBB
CCCCCCCC
DDDDDDD
EEEEEE
FFFFF
GGGG
HHH
II
J


In [27]:
n= int(input("enter the numbers"))
for i in range(n):
    for j in range(n-i):
        print(chr(64+j+1),end='')
    print()

enter the numbers10
ABCDEFGHIJ
ABCDEFGHI
ABCDEFGH
ABCDEFG
ABCDEF
ABCDE
ABCD
ABC
AB
A


In [32]:
n= int(input('Enter the iterations'))#5
for i in range(n): #5 
    for j in range(n-i): #5 times
        print(n-j,end='') # 5 times
    print()# 5

Enter the iterations10
10987654321
1098765432
109876543
10987654
1098765
109876
10987
1098
109
10


In [39]:
n = int(input('enter the iterations'))
for i in range(1,n+1):
    for j in range(n+1-i):
        print(chr(75-i),end='')
    print()

enter the iterations10
JJJJJJJJJJ
IIIIIIIII
HHHHHHHH
GGGGGGG
FFFFFF
EEEEE
DDDD
CCC
BB
A


In [48]:
for i in range(1,11):
    for j in range(11-i):
        print(chr(74-j),end='')
    print()

JIHGFEDCBA
JIHGFEDCB
JIHGFEDC
JIHGFED
JIHGFE
JIHGF
JIHG
JIH
JI
J


In [68]:
for i in range(11):
    #var= '*'*i
    print(str('*'*i).center(11,' '))
    #for j in range(10-i):
        #print('*')
    #print()

           
     *     
     **    
    ***    
    ****   
   *****   
   ******  
  *******  
  ******** 
 ********* 
 **********


In [91]:
for i in range(1,11):
    for j in range(i):
        print('*',end='')
    print()

*
**
***
****
*****
******
*******
********
*********
**********


In [130]:
class operations():
    def __init__(self,x,y):
        self.x = x
        self.y = y
        self.c=0
    def add_num(self):
        self.c = self.x+self.y
        return self.c
    def sub_num(self):
        self.c = self.x-self.y
        return self.c
    def __str__(self):
        return self.c

In [131]:
a = operations(10,20)
a.add_num()

30

In [122]:
a

In [201]:
class zoo():
    def __init__(self,D):
        self.D=D
    def add_animals(self,Key,Value):
        self.D[Key]=Value
        return self.D
    def gone_animals(self,Key,Value):
        for Key in self.D.keys():     
            if self.D[Key]>Value:
                self.D[Key]=self.D[Key]-Value
            else:
                del D[Key]
        return self.D
    def highest_animals(self):
            l=[]
            z=max(self.D.values())
            for Key in self.D:
                if self.D[Key]==z:
                    l.append(Key)
            return l
#     def lowest_animals(self):
#         min(self.D[Value])
#         return self.D   
    def __str__(self):
        return self.D

In [202]:
B={} 
B['Bala']=6
B['donkey']=8
B

{'Bala': 6, 'donkey': 8}

In [203]:
model = zoo(B)
model.add_animals('Buffalo',20)

{'Bala': 6, 'donkey': 8, 'Buffalo': 20}

In [204]:
model.highest_animals()

['Buffalo']

In [205]:
model.gone_animals('Buffalo',2)

{'Bala': 4, 'donkey': 6, 'Buffalo': 18}

In [ ]:
changes on gi

In [208]:
import array as arr
import numpy
val  = arr.array('i',[10,20,30,40],[20,30,40,50])
newarr= arr.array(val.typecode,(a for a in val))
i=0
while i <len(newarr):
    print(newarr[i])
    i+=1

TypeError: array() argument 1 must be a unicode character, not list

In [225]:
from numpy import *
arr=array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [226]:
arr=arr*5
arr

array([ 5, 10, 15, 20])

In [227]:
arr2=array([1,3,4,5])
arr2

array([1, 3, 4, 5])

In [228]:
final=arr+arr2
final

array([ 6, 13, 19, 25])

In [231]:
print(sqrt(final))


[2.44948974 3.60555128 4.35889894 5.        ]
63


In [232]:
print(sum(final))

63


In [233]:
print(max(final))

25


In [235]:
print(concatenate([arr,arr2]))

[ 5 10 15 20  1  3  4  5]


In [333]:
from numpy import *
Mularray = array([
                
                [1,2,3],
                [4,5,6],
                [3,4,5],
                [1,2,3],
                [4,5,6],
                [3,4,5]
                
                    ])

In [334]:
Mularray

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 5],
       [1, 2, 3],
       [4, 5, 6],
       [3, 4, 5]])

In [327]:
print(Mularray.shape)

(3, 3)


In [328]:
print(Mularray.flatten())

[1 2 3 4 5 6 3 4 5]


In [335]:
print(Mularray.reshape(2,3,3))

[[[1 2 3]
  [4 5 6]
  [3 4 5]]

 [[1 2 3]
  [4 5 6]
  [3 4 5]]]


In [336]:
#Matrices:
ar = array([  
            [1,2,3,4],
            [4,5,6,7]
            ])


In [337]:
m = matrix(ar)
print(m)

[[1 2 3 4]
 [4 5 6 7]]


In [341]:
m = matrix('1 2 3;4 5 6;7 8 9')
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [342]:
#diagonal of a matrix
z = diagonal(m)
print(z)

[1 5 9]


In [345]:
# min of the matrix
print(m.min())
print(m.max())

1
9


In [348]:
m1=matrix('1 2 3;4 5 6;7 8 9')
m2=matrix('1 2 3;4 5 6;7 8 9')
m3=m1+m2
print(m3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [315]:
class animal():
    def __init__(self,age):
        self.age = age
        self.name = None
    def getage(self):
        return self.age
    def getname(self):
        return self.name
    def setage(self,newage=''):
        self.age = newage
        return self.age
    def setname(self,name):
        self.name = name
        return self.name
    def __str__(self):
        return str(self.name)+', '+str(self.age)

In [316]:
a = animal(10)

In [317]:
type(a)

__main__.animal

In [320]:
a.getage()

''

In [311]:
a.getname()

In [319]:
a.setage()

''

In [313]:
a.setname('string')

'string'

In [314]:
print(a)

string, 30


In [324]:
self.a = 1

NameError: name 'self' is not defined

In [322]:
sai =[]

In [355]:
#functions:

def greet():
    print("Hello")
    print("Good Morning")

In [356]:
greet()

Hello
Good Morning


In [361]:
#add two numbers
def add(x,y):
    c=x+y
    return c

In [368]:
result=add(4,5)
print(result)

9


In [370]:
#add two numbers
def add_sub(x,y):
    c=x+y
    d=x-y
    return c,d

In [372]:
result1,result2=add_sub(5,4)

In [373]:
print(result1,result2)

9 1


In [2]:
# funcion 
def update(x):
    x=8
    print(x)
update(10)

8


In [5]:
# pass by value 
def update(x):
    print(id(x))
    x=10
    print("x",x)

a=10
print(id(a))
update(a)
print("a",(a))

140704658827344
140704658827344
x 10
a 10


In [6]:
# pass by reference 
def update(x):
    print(id(x))
    x=8
    print(id(x))
    print("x",x)

a=10
print(id(a))
update(a)
print("a",(a))

140704658827344
140704658827344
140704658827280
x 8
a 10


In [2]:
# list funcion  still it is mutable, the address doesnt change
def update(lst):
    print(id(lst))
    lst[1]=8
    print(id(lst))
    print("updated lst",lst)

lst=[10,20,30]
print(id(lst))
update(lst)
print("lst",(lst))

1319004035648
1319004035648
1319004035648
updated lst [10, 8, 30]
lst [10, 8, 30]


In [10]:
#pass the args in the different way
def add(a,*b):
    c=0
    for i in b:
        c+=i
    print(c)

add(10,20,30,50)

100


In [13]:
# Keyworded Variable Length Arguments in Python **kwargs

def person(name,**data):
    print(name)
    for i,j in data.items():
        print(i,j)

person('sai',age = 28,city='mumbai',mob=9239230232)


sai
age 28
city mumbai
mob 9239230232


In [27]:
#Global Keyword in Python | Global vs Local Variable

a= 10
print(id(a))
def inside():
    global a
    print(id(a))
    print(a)
    a=20
    print(id(a))
    print("inside",a)
inside()
print("outside",a)    

140704658827344
140704658827344
10
140704658827664
inside 20
outside 20


In [31]:
a=10  # global variable a=10
print(id(a))
def something():
    a=9    # local variable a=9 
    x=globals()['a'] # globals keyword act as local & global
    print(id(x))   # get the access of global variable 'a' & x=10
    print("inside",a)
    globals()['a']=15   # new value of a 
    
something() # call something function , initially a = 9

print("outside",a)

140704658827344
140704658827344
inside 9
outside 15


In [38]:
# Pass List to a Function in Python

def count(lst):
    even=0
    odd=0
    for i in lst:
        if i%2==0:
            even+=1
        else:
            odd+=1
    return even,odd

lst=[10,20,23,43,53,60,70,80]
even,odd= count(lst)
print("Even:{} and odd:{}".format(even,odd))

Even:5 and odd:3


In [40]:
import re
x='My 2 favourite numbers are 19 and 42'
match = re.search('[0-9]+',x)
print(match.group())
print(match.start())
print(match.end())
print(match.span())

2
3
4
(3, 4)


In [50]:
matches = re.findall('[0-9]+',x)
print(matches)
matches=re.findall('ATEXT',x)
print(matches)

['2', '19', '42']
[]


In [92]:
#Iterators 

L=[1,2,3,4,5]
it1=iter(L)

In [93]:
print(next(it1))

#or 
#it3.__next__()

1


In [94]:
print(next(it1))

2


In [95]:
print(next(it1))

3


In [96]:
print(next(it1))

4


In [97]:
print(next(it1))

5


In [100]:
it4=L.__iter__()

In [101]:
next(it4)

1

In [104]:
# iterators for loop by using interpreter
for i in L:
    print(i)

1
2
3
4
5


In [110]:
#Fibonacci():
class Fibonacci():
    def __init__(self):
        self.a,self.b=0,1
    def __iter__(self):
        return(self)
        
    def __next__(self):
        prev = self.a
        self.a,self.b=self.b,self.a+self.b
        return prev

In [111]:
f= iter(Fibonacci())
for i in range(10):
    print(next(f))

0
1
1
2
3
5
8
13
21
34


In [114]:
#instead of above for loop 
for j,i in zip(range(10), Fibonacci()):
    print(j,i)
# j is index and i is Fibonacci series 

0 0
1 1
2 1
3 2
4 3
5 5
6 8
7 13
8 21
9 34


In [124]:
# implementation of generator function 
def fibonacci(n):
    a,b=1,1
    for _ in range(n):
        a,b=a+b,a
        yield a


In [125]:
for f in fibonacci(20):
    print(f)        

2
3
5
8
13
21
34
55
89
144
233
377
610
987
1597
2584
4181
6765
10946
17711


In [ ]:
def fibonacci(n):
    a,b=0,1
    for _ in range(n):
        prev=a
        a,b=b,a+b
        yield prev

In [139]:
for i in fibonacci(5):
    print(i)

2
3
5
8
13


In [140]:
# differenc between yield and return

def mygenerator():
    print('First item')
    yield 10

    return

    print('Second item')
    yield 20

    print('Last item')
    yield 30
    

In [141]:
gen = mygenerator()
next(gen)

First item


10

In [142]:
next(gen)

StopIteration: 

In [145]:
def get_sequence_upto(x):
    for i in range(x):
        yield i

In [146]:
seq = get_sequence_upto(5) 

In [147]:
next(seq)

0

In [148]:
next(seq)

1

In [149]:
next(seq)

2

In [127]:
x=10;y=20
x,y=y,x
print(x,y)

20 10


In [133]:

def gen():
    yield 3
    yield 4

value = gen()

print(value.__next__())

3


In [130]:
print(value.__next__())

4


In [138]:
def gen():
    value=3
    return value
#    return 4

value = gen()
print(value)

3


In [151]:
#List comprehensions;
o=[]
for i in [1,2,3,4,5]:
    o.append(i*i)
print(o)

[1, 4, 9, 16, 25]


In [152]:
# Efficient way for list comprehension
[i*i for i in [1,2,3,4,5]]

[1, 4, 9, 16, 25]

In [190]:
[i*i for i in range(10) if i%2]

[1, 9, 25, 49, 81]

In [173]:
[i*i for i in range(10) if i%2==0]

1

In [2]:
#fibonacci series
def fibonacci(n):
    a,b=0,1
    for _ in range(n):
        prev=a
        a,b=b,a+b
        yield prev

In [3]:
[i for i in fibonacci(10)]

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]

In [4]:
[x for x in range(10,100) if x in fibonacci(100)]

[13, 21, 34, 55, 89]

In [5]:
[x for x in fibonacci(10) if x%2==0]

[0, 2, 8, 34]

In [6]:
(x for x in fibonacci(10) if x%2==0)

<generator object <genexpr> at 0x000002B7DEFAF5F0>

In [7]:
(x for x in fibonacci(100000) if x%2==0)

<generator object <genexpr> at 0x000002B7DEFAF820>

In [11]:
it=(x for x in fibonacci(100) if x%2==0)
for i in range(100000):
    print(next(it))

0
2
8
34
144
610
2584
10946
46368
196418
832040
3524578
14930352
63245986
267914296
1134903170
4807526976
20365011074
86267571272
365435296162
1548008755920
6557470319842
27777890035288
117669030460994
498454011879264
2111485077978050
8944394323791464
37889062373143906
160500643816367088
679891637638612258
2880067194370816120
12200160415121876738
51680708854858323072
218922995834555169026


StopIteration: 

In [ ]:
#lambda expressions